import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';


export enum ApiVersion {
  V1_0 = '/v1.0',
  V1_5 = '/v1.5',
  V1_6 = '/v1.6',
  V2_0 = '/v2.0',
  V2_1 = '/v2.1',
  V2_5 = '/v2.5',
  V2_6 = '/v2.6',
  V2_7 = '/v2.7',
  V2_8 = '/v2.8',
  V2_9 = '/v2.9',
  V3_0 = '/v3.0',
  V3_1 = '/v3.1',
  V3_2 = '/v3.2',
  V3_3 = '/v3.3',
  V3_4 = '/v3.4',
  V3_5 = '/v3.5',
  V3_6 = '/v3.6',
  V3_7 = '/v3.7',
  V3_8 = '/v3.8',
  V3_9 = '/v3.9',
  V2_GATEWAY = '.execute-api.us-west-2.amazonaws.com/'
}


export const EndPoint = {
  'VALIDATE_COMPANY': `${ApiVersion.V1_5}/company/validate_company`,
  'VALIDATE_EMAIL': `${ApiVersion.V1_5}/login/check_login_email`,
  'LOGIN': `${ApiVersion.V1_5}/auth/login`,
  'GET_COMPANIES': `${ApiVersion.V1_6}/retrieve_company`,
  'GET_COUNTRIES': `${ApiVersion.V1_5}/user/get_country`,
  'GET_STATES': `${ApiVersion.V1_5}/user/get_states/`,
  'FORGOT_PWD': `${ApiVersion.V1_5}/user/forgot_password`,
  'LOGOUT': `${ApiVersion.V1_5}/user/user_logout`,
  'UPDATE_PASSWORD': `${ApiVersion.V1_6}/user/update_password`,
  'UPDATE_COMPANY': `${ApiVersion.V1_6}/company/update_company`,
  'GET_TIMEZONE': `${ApiVersion.V1_6}/get_timezone`,
  'ADD_COMPANY': `${ApiVersion.V1_6}/company/add_company`,
  'DELETE_COMPANY': `${ApiVersion.V1_6}/company/delete_company`,
  'COMPANY_DETAILS': `${ApiVersion.V1_6}/company/company_details`,
  'GET_BRANDING': `${ApiVersion.V1_6}/company/get_company_branding`,
  'UPDATE_BRANDING': `${ApiVersion.V1_6}/company/update_company_branding`,
  'DELETE_ASSET': `${ApiVersion.V1_6}/company/delete_company_branding`,
  'GET_LOCATIONS': `${ApiVersion.V1_6}/location/retrieve_location`,
  'GET_DEPARTMENTS': `${ApiVersion.V1_6}/department/retrieve_department`,
  'GET_LOCATIONS_DEPARTMENTS_SOM': `${ApiVersion.V1_6}/manager/get_managers_locations_and_departments`,
  'GET_GAMES': `${ApiVersion.V1_6}/game/retrieve_game`,
  'DELETE_GAME': `${ApiVersion.V1_6}/game/delete`,
  'COPY_GAME': `${ApiVersion.V1_6}/game/copy_game`,
  'ADD_GAME': `${ApiVersion.V1_6}/game/add`,
  'UPDATE_GAME': `${ApiVersion.V1_6}/game/update`,
  'UPDATE_GAME_STATE': `${ApiVersion.V1_6}/game/update_game_state`,
  'GET_GAME_PROFILES': `${ApiVersion.V1_6}/profile/retrieve_profile`,
  'GET_GAME_LIMITS': `${ApiVersion.V1_6}/gamelimit/retrieve_game_limit`,
  
  'ADD_LIMIT_EVERYONE': `${ApiVersion.V1_6}/gamelimit/add_location_everyone`,
  'UPDATE_LIMIT': `${ApiVersion.V1_6}/gamelimit/edit_location_everyone`,
  'DELETE_LIMIT': `${ApiVersion.V1_6}/gamelimit/delete`,
  'MOVE_QUESTIONS': `${ApiVersion.V1_6}/category/move_questions`,
  'COPY_QUESTIONS': `${ApiVersion.V1_6}/category/copy_questions`,
  'COPY_QUESTIONS_PROGRESS': `${ApiVersion.V1_6}/category/copy_questions_progress`,
  'ADD_QUESTION_CATEGORY': `${ApiVersion.V1_6}/category/add_category`,
  'DELETE_QUESTION_CATEGORY': `${ApiVersion.V1_6}/category/delete`,
  'UPDATE_QUESTION_CATEGORY': `${ApiVersion.V1_6}/category/update_category`,
  'UPDATE_QUESTIONS_POINTS_TIME': `${ApiVersion.V1_6}/question/reset_questions_points_and_time`,
  'GAME_ICONS': `${ApiVersion.V1_6}/game/get_icon_game_list`,
  'VALIDATE_GAME_READINESS': `${ApiVersion.V1_6}/game/validate_game_readyness`,
  'GET_GAME_CATEGORIES': `${ApiVersion.V1_6}/game/game_categories`,
  'GET_GAME_DETAILS': `${ApiVersion.V1_6}/game/game_details`,
  'DELETE_DEPARTMENT': `${ApiVersion.V1_6}/department/delete`,
  'GET_GROUPS': `${ApiVersion.V1_6}/group/retrieve_group`,
  'ADD_LOCATION': `${ApiVersion.V1_6}/location/add_location`,
  'UPDATE_LOCATION': `${ApiVersion.V1_6}/location/update`,
  'DELETE_LOCATION': `${ApiVersion.V1_6}/location/delete_location`,
  'ADD_GROUP': `${ApiVersion.V1_6}/group/add`,
  'GET_GROUP_DETAILS': `${ApiVersion.V1_6}/group/group_details`,
  'UPDATE_GROUP': `${ApiVersion.V1_6}/group/update`,
  'DELETE_GROUP': `${ApiVersion.V1_6}/group/delete`,
  'SETTINGS': `${ApiVersion.V1_6}/get_company_settings`,
  'ADD_DEPARTMENT': `${ApiVersion.V1_6}/department/add`,
  'UPDATE_DEPARTMENT': `${ApiVersion.V1_6}/department/update`,
  'GET_PERMISSIONS': `${ApiVersion.V1_6}/auth/get_permissions`,
  'GET_AWS_TOKEN': `${ApiVersion.V3_0}/resources/config?is_admin=true`,
  'GET_FAQS': `${ApiVersion.V1_6}/faq/retrieve_faq`,
  'GET_QUESTIONS': `${ApiVersion.V1_6}/question/retrieve_question`,
  'UPLOAD_QUESTIONS': `${ApiVersion.V1_6}/question/upload_question`,
  'UPDATE_QUESTIONS_STATE': `${ApiVersion.V1_6}/question/update_status`,
  'GET_QUESTION_CATEGORIES': `${ApiVersion.V1_6}/game/game_question_categories`,

  'ADD_QUESTION': `${ApiVersion.V3_5}/question/add_question`,
  'UPDATE_QUESTION': `${ApiVersion.V3_5}/question/update_question`,

  'DELETE_FAQ': `${ApiVersion.V1_6}/faq/delete`,
  'UPDATE_FAQ': `${ApiVersion.V1_6}/faq/update`,
  'ADD_FAQ': `${ApiVersion.V1_6}/faq/add`,
  'GET_PLAYERS': `${ApiVersion.V1_6}/player/retrieve_player`,
  'ADD_PLAYER': `${ApiVersion.V1_6}/player/add_player`,
  'UPDATE_PLAYER': `${ApiVersion.V1_6}/player/edit_player`,
  'DELETE_PLAYER': `${ApiVersion.V1_6}/player/delete_player`,
  'UPDATE_PLAYER_STATUS': `${ApiVersion.V1_6}/player/update_status`,
  'GET_OWNERS': `${ApiVersion.V1_6}/manager/retrieve_game_owners`,
  'GET_MANAGERS': `${ApiVersion.V1_6}/manager/retrieve_manager`,
  'GET_VIP_CODE': `${ApiVersion.V1_6}/vip_code/get_vip_code_list`,
  'ADD_MANAGER': `${ApiVersion.V1_6}/manager/add_manager`,
  'UPDATE_MANAGER': `${ApiVersion.V1_6}/manager/update`,
  'DELETE_MANAGER': `${ApiVersion.V1_6}/manager/delete`,
  'UPDATE_MANAGER_STATUS': `${ApiVersion.V1_6}/manager/active_deactive`,
  'GET_PLAYER_DETAILS': `${ApiVersion.V1_6}/player/player_details`,
  'GET_MANAGER_DETAILS': `${ApiVersion.V1_6}/manager/manager_details`,
  'GET_ETHNICITY': `${ApiVersion.V1_5}/company/ethnicity`,
  'BULK_UPDATE_PLAYER': `${ApiVersion.V1_6}/player/bulk_update`,
  'OBOARDING_EMAIL': `${ApiVersion.V1_5}/player/send_onboarding`,
  'ADD_PROFILE': `${ApiVersion.V1_6}/profile/add`,
  'UPDATE_PROFILE': `${ApiVersion.V1_6}/profile/update`,
  'LINK_PROFILE': `${ApiVersion.V1_6}/game/link_profile`,
  'UNLINK_PROFILE': `${ApiVersion.V1_6}/game/unlink_profile`,
  'DELETE_PROFILE': `${ApiVersion.V1_6}/profile/delete`,
  'DOWNLOAD_MANAGERS': `${ApiVersion.V1_6}/manager/download_manager`,
  'DOWNLOAD_QUESTIONS': `${ApiVersion.V1_6}/question/download_question`,
  'UPLOAD_PLAYER': `${ApiVersion.V1_6}/player/upload_player`,

  'GAMES_PLAYED_BY_TEAM': `${ApiVersion.V2_9}/report/total_games_played_by_team`,
  'TROPHY_ACHIEVED_BY_TEAM': `${ApiVersion.V2_9}/report/trophies_by_team`,
  'PARTICIPATION_BY_TEAM': `${ApiVersion.V2_9}/report/participation_by_team`,
  'LEADERBOARD_BY_TEAM': `${ApiVersion.V2_9}/report/leaderboard_by_team`,
  'LEADERBOARD_BY_CONTEST': `${ApiVersion.V2_9}/report/leaderboard_by_contest`,
  'TOTAL_PLAYED_BY_GAME': `${ApiVersion.V2_9}/report/total_games_played_by_game`,
  'TROPHY_ACHIEVED_BY_GAME': `${ApiVersion.V2_9}/report/trophies_by_game`,
  'PARTICIPATION_BY_GAME': `${ApiVersion.V2_9}/report/participation_by_game`,
  'WINRATE_BY_GAME': `${ApiVersion.V2_9}/report/get_game_winrate`,
  'LEADERBOARD_BY_GAME': `${ApiVersion.V2_9}/report/leaderboard_by_game`,
  'GAMES_PLAYED_BY_PLAYER': `${ApiVersion.V2_9}/report/total_games_played_by_player`,
  'PARTICIPATION_BY_PLAYER': `${ApiVersion.V2_9}/report/participation_by_player`,
  'TROPHY_ACHIEVED_BY_PLAYER': `${ApiVersion.V2_9}/report/trophies_by_player`,
  'DOWNLOAD_TROPHY_REPORT': `${ApiVersion.V2_9}/trophy/download_trophy_reports`,

  'GET_TROPHY_REPORT': `${ApiVersion.V2_9}/trophy/get_trophy_details_and_reports`,
  'GET_MLG_TROPHY': `${ApiVersion.V2_9}/report/get_mlg_trophy`,
  'GET_TROPHIES_BY_REPORT': `${ApiVersion.V2_9}/trophy/view_trophies`,

  'GET_TROPHIES_BY': `${ApiVersion.V1_6}/trophy/view_trophies`,
  'GET_GAMES_TROPHY': `${ApiVersion.V1_6}/game/retrieve_unset_trophy_games?`,
  'ADD_GAME_TROPHY': `${ApiVersion.V1_6}/trophy/add_trophies?`,
  'EDIT_GAME_TROPHY': `${ApiVersion.V1_6}/trophy/edit_trophies?`,
  'GET_PLAYER_GAMEPLAY': `${ApiVersion.V2_9}/report/players_gameplay_statistics`,
  'GET_SP_GAME_HISTORY': `${ApiVersion.V2_9}/report/get_sp_game_history`,
  'GET_MP_GAME_HISTORY': `${ApiVersion.V2_9}/report/get_mp_game_history`,
  'GET_MLG_GAMES_HISTORY': `${ApiVersion.V3_2}/player/dashboard/get_player_mlg_details`,
  'GET_SHOP_GAME_HISTORY': `${ApiVersion.V3_3}/report/get_shop_game_history`,
  
  'GET_LEVELS_ACHIEVED': `${ApiVersion.V2_9}/level/get_levels`,
  'GET_TROPHIES_ACHIEVED': `${ApiVersion.V2_9}/trophy/get_player_trophies`,
  'GET_PLAYER_ACHIVMENTS': `${ApiVersion.V3_2}/player/dashboard/get_player_achievement`,
  'GET_SP_GAME_SESSION_DETAILS': `${ApiVersion.V2_9}/report/get_sp_game_session_details`,
  'GET_MP_GAME_SESSION_DETAILS': `${ApiVersion.V2_9}/report/get_mp_game_session_details`,
  'GET_DETAIL_REPORT': `${ApiVersion.V2_9}/report/get_detail_report`,
  'DETAILED_REPORT': `${ApiVersion.V2_9}/report/download_detail_report`,
  'DOWNLOAD_PLAYER_GAMEPLAY_STATS': `${ApiVersion.V2_9}/report/download_players_gameplay_statistics`,
  'CONTEST_VIEW_TROPHY': `${ApiVersion.V2_9}/contest/view_trophies`,
  'MLG_VIEW_TROPHY': `${ApiVersion.V2_9}/mlg/retrieve_live_deleted_mlgs`,
  'MLG_TROPHY_DETAILS': `${ApiVersion.V2_9}/mlg/retrieve_trophy_report`,
  'DOWNLOAD_CONTEST_TROPHY': `${ApiVersion.V2_9}/report/download_contest_trophy_report`,
  'DOWNLOAD_SP_GAME_HISTORY': `${ApiVersion.V2_9}/report/download_sp_game_history`,
  'DOWNLOAD_MP_GAME_HISTORY': `${ApiVersion.V2_9}/report/download_mp_game_history`,
  'DOWNLOAD_SHOP_GAME_HISTORY': `${ApiVersion.V3_3}/report/download_shop_game_history`,
  'DOWNLOAD_SP_GAME_SESSION_DETAILS': `${ApiVersion.V2_9}/report/download_sp_game_session_details`,
  'DOWNLOAD_MP_GAME_SESSION_DETAILS': `${ApiVersion.V2_9}/report/download_mp_game_session_details`,
  'TIME_SPENT_BY_CONTEST': `${ApiVersion.V2_9}/report/total_time_spend_by_contest`,

  'GET_QUESTION_REPORT': `${ApiVersion.V1_6}/report/get_correct_incorrect_question_data`,
  'DOWNLOAD_QUESTION_REPORT': `${ApiVersion.V1_6}/report/download_correct_incorrect_question_data`,
  'GET_NOTIFICATION_SETTINGS': `${ApiVersion.V1_6}/notification/get_notification_settings`,
  'UPDATE_NOTIFICATION_SETTINGS': `${ApiVersion.V1_6}/notification/update_notification_settings`,
  'SEND_CUSTOM_NOTIFICATION': `${ApiVersion.V1_6}/notification/send_custom_notification`,
  'RETREIVE_FEEDBACK': `${ApiVersion.V1_6}/feedback/retrieve_feedback?`,
  'DOWNLOAD_FEEDBACK_REPORT': `${ApiVersion.V1_6}/feedback/download_players_feedback?`,
  'ADD_PLAYER_ATTEMPTS': `${ApiVersion.V1_6}/gamelimit/add_attempt`,
  'UPDATE_PLAYER_ATTEMPTS': `${ApiVersion.V1_6}/gamelimit/edit_attempt`,
  'DELETE_PLAYER_ATTEMPTS': `${ApiVersion.V1_6}/gamelimit/delete_attempt`,
  'RESOLVE_FEEDBACK': `${ApiVersion.V1_6}/feedback/update_feedback`,
  'DELETE_LIVE_GAME_SESSIONS': `${ApiVersion.V1_6}/gamelimit/delete_incomplete_game_session`,
  'GET_DEPT_BY_LOCATIONS': `${ApiVersion.V1_6}/department/get_department_by_locations`,
  'GET_TIPS': `${ApiVersion.V1_6}/manager/retrieve_manager_tips`,
  'UPDATE_TIPS': `${ApiVersion.V1_6}/manager/edit_tips`,
  'GAME_ACCURACY_REPORT': `${ApiVersion.V1_6}/report/download_game_accuracy_report`,
  'MASTER_REPORT': `${ApiVersion.V1_6}/report/download_active_player_report`,
  'GET_FIELDS': `${ApiVersion.V1_6}/game_schedule/get_fields`,
  'GET_VALUES': `${ApiVersion.V1_6}/game_schedule/get_values`,
  'GET_GAME_SCHEDULE': `${ApiVersion.V1_6}/game_schedule/get_limits`,
  'ADD_GAME_SCHEDULE': `${ApiVersion.V1_6}/game_schedule/add_limits`,
  'UPDATE_GAME_SCHEDULE': `${ApiVersion.V1_6}/game_schedule/edit_limits`,
  'DELETE_GAME_SCHEDULE': `${ApiVersion.V1_6}/game_schedule/delete_limits`,
  'GET_CONTESTS_LIST': `${ApiVersion.V2_0}/contest/retrieve_contests`,
  'GET_CONTEST': `${ApiVersion.V2_0}/contest/contest_details`,
  'GET_CONTEST_GAMES': `${ApiVersion.V2_0}/contest/retrieve_contest_games`,
  'CREATE_VIP_CODE': `${ApiVersion.V1_6}/vip_code/add_vip_code`,
  'REACTIVATE_VIP_CODE': `${ApiVersion.V1_6}/vip_code/reactivate`,
  'VIP_CODE_STATUS': `${ApiVersion.V1_6}/vip_code/change_vip_code_state`,
  'COMPANY_GAME_REPORT': `${ApiVersion.V1_6}/report/company_wide_gameplay_report`,
  'CREAT_CONTEST': `${ApiVersion.V2_0}/contest/add`,
  'ADD_GAME_TO_CONTEST': `${ApiVersion.V2_0}/contest/add_game_to_contest`,
  'UPDATE_CONTEST': `${ApiVersion.V2_0}/contest/update`,
  'UPDATE_GAMES_CONTEST': `${ApiVersion.V2_0}/contest/update_games_in_contest`,
  'PUBLISH': `${ApiVersion.V2_0}/contest/publish`,
  'GET_CONTEST_REWARD_CATEGORY': `${ApiVersion.V2_0}/contest/retrieve_contest_reward_category`,
  'GET_CONTEST_REWARD': `${ApiVersion.V2_0}/contest/retrieve_contest_rewards`,

  'GET_CONTEST_ASSIGNMENT': `${ApiVersion.V2_0}/contest/get_assignment`,
  'ADD_CONTEST_ASSIGNMENT': `${ApiVersion.V2_0}/contest/add_assignment`,
  'UPDATE_CONTEST_ASSIGNMENT': `${ApiVersion.V2_0}/contest/update_assignment`,


  'DELETE_CONTEST': `${ApiVersion.V2_0}/contest/delete`,
  'DELETE_GAMES_IN_CONTEST': `${ApiVersion.V2_0}/contest/remove_games`,
  'FORCE_CLOSE_CONTEST': `${ApiVersion.V2_0}/contest/forced_close`,
  'MOVE_CONTEST_TO_DRAFT': `${ApiVersion.V2_0}/contest/ready_to_draft`,
  'GET_CUSTOM_MANAGER_LIST': `${ApiVersion.V1_6}/game_schedule/get_custom_managers`,
  'ADD_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/add`,
  'DELETE_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/delete`,
  'UPDATE_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/update`,
  'GET_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/retrieve_mlgs`,
  'GET_MULTILEVEL_GAME_DETAILS': `${ApiVersion.V2_1}/mlg/mlg_details`,
  'ADD_GAMES_IN_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/add_level`,
  'UPDATE_GAME_IN_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/update_level`,
  'DELETE_GAME_IN_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/delete_level`,
  'GET_VALID_CONTEST_DATE': `${ApiVersion.V2_0}/contest/get_valid_contest_date`,
  'COPY_GAME_TO_COMPANIES': `${ApiVersion.V1_6}/game/copy_game_to_other_companies`,
  'MLG_COPY_GAME': `${ApiVersion.V2_1}/mlg/copy_mlg_game`,
  'MLG_COPY_PROGRESS': `${ApiVersion.V2_1}/mlg/copy_mlg_progress`,
  'ADD_MULTILEVEL_GAME_ASSIGNMENT': `${ApiVersion.V2_1}/mlg/add_assignment`,
  'GET_MULTILEVEL_GAME_ASSIGNMENT': `${ApiVersion.V2_1}/mlg/get_assignment`,
  'SET_MULTILEVEL_GAME_ASSIGNMENT': `${ApiVersion.V2_1}/mlg/set_assignment`,
  'CHECK_MULTILEVEL_GAME_READINESS': `${ApiVersion.V2_1}/mlg/check_readiness`,
  'GET_HIERARCHY_REPORT': `${ApiVersion.V1_6}/reportee/get_reportee_hierarchy`,
  'GET_COMPANY_STATISTICS': `${ApiVersion.V1_6}/company/paywall_statistics`,
  'GET_CSR': `${ApiVersion.V1_6}/company/retrieve_csr`,
  'GET_SDR': `${ApiVersion.V1_6}/company/retrieve_sdr`,
  'GET_MARKETPLACE_GAME_CATEGORIES': `${ApiVersion.V2_1}/shop/get_market_place_categories`,
  'GET_MARKETPLACE_BANNER_IMAGE': `${ApiVersion.V2_1}/shop/get_shop_home_banner_image`,
  'ADD_GAME_TO_MARKETPLACE': `${ApiVersion.V2_1}/shop/add_game_library_to_marketplace`,
  'UPDATE_MARKETPLACE_BANNER_IMAGE': `${ApiVersion.V2_1}/shop/upload_shop_banner_image`,
  'GET_MARKETPLACE_GAMES_BY_CATEGORY': `${ApiVersion.V2_1}/shop/get_marketplace_games_by_category`,
  'ADD_GAME_MARKETPLACE_TO_LIBRARY': `${ApiVersion.V2_1}/shop/add_game_marketplace_to_library`,
  'GET_GAME_CATEGORY': `${ApiVersion.V2_5}/category/retrieve_game_category`,
  'ADD_GAME_CATEGORY': `${ApiVersion.V2_5}/category/add_category`,
  'UPDATE_GAME_CATEGORY': `${ApiVersion.V2_5}/category/update_category`,
  'DELETE_GAME_CATEGORY': `${ApiVersion.V2_5}/category/delete_category`,
  'GET_GAME_COUNT': `${ApiVersion.V2_5}/category/retrieve_game_count`,
  'REMOVE_MARKETPLACE_GAME': `${ApiVersion.V2_1}/shop/remove_marketplace_game`,
  'UPDATE_MARKETPLACE_GAME': `${ApiVersion.V2_1}/shop/updateGameDetails`,
  'CHECK_USAGE_LIMIT': `${ApiVersion.V2_6}/company/check_metric_limit`,
  'GET_GAME_PREVIEW_DETAILS': `${ApiVersion.V2_1}/shop/get_game_preview_details`,
  'UPDATE_SHOP_GAME_PREVIEW_DETAILS': `${ApiVersion.V2_1}/shop/update_game_preview_details`,
  'ARCHIVE_GAME': `${ApiVersion.V1_6}/game/archive`,
  'UNARCHIVE_GAME': `${ApiVersion.V1_6}/game/unarchive`,
  'GET_GAMES_CONTEST': `${ApiVersion.V2_0}/contest/get_games_for_filter`,
  'UPDATE_SHOP_GAME_POSITION': `${ApiVersion.V2_1}/shop/update_shop_game_position`,
  'ADD_LEARNING_ASSETS': `${ApiVersion.V2_8}/user/add_learning_assets`,
  'USER_ONBOARD': `${ApiVersion.V2_8}/user/onboard_user`,
  'USER_ONBOARD_GATEWAY': `6s4k6zcy77${ApiVersion.V2_GATEWAY}${environment.gateway_environment}`,
  'COMPANY_CATEGORY_DETAILS_GATEWAY': `ok1zsjdaz6${ApiVersion.V2_GATEWAY}${environment.gateway_environment}`,
  'COMPANY_SETUP_DETAILS_GATEWAY': `h6iqhy0a92${ApiVersion.V2_GATEWAY}${environment.gateway_environment}`,
  'PERSONAL_DETAILS_GATEWAY': `2f2isrolj2${ApiVersion.V2_GATEWAY}${environment.gateway_environment}`,
  'GET_USER_CATEGORY_GATEWAY': `raxylau9ed${ApiVersion.V2_GATEWAY}${environment.gateway_environment}`,
  'GET_CUSTOM_AUDIENCE': `${ApiVersion.V2_8}/custom_audience/retrieve_audience`,
  'GET_CUSTOM_AUDIENCE_DETAILS': `${ApiVersion.V2_8}/custom_audience/audience_details`,
  'VALIDATE_AUDIENCE_NAME': `${ApiVersion.V2_8}/custom_audience/validate_audience_name`,
  'ADD_CUSTOM_AUDIENCE': `${ApiVersion.V2_8}/custom_audience/add_audience`,
  'UPDATE_CUSTOM_AUDIENCE': `${ApiVersion.V2_8}/custom_audience/edit_audience`,
  'DELETE_CUSTOM_AUDIENCE': `${ApiVersion.V2_8}/custom_audience/delete_audience`,
  'GET_AUDIENCE_GAME_LIMIT': `${ApiVersion.V2_8}/custom_audience/retrieve_game_audience_limit`,
  'ADD_AUDIENCE_GAME_LIMIT': `${ApiVersion.V2_8}/custom_audience/add_game_limit`,
  'UPDATE_AUDIENCE_LIMIT': `${ApiVersion.V2_8}/custom_audience/edit_game_limit`,
  'DELETE_AUDIENCE_LIMIT': `${ApiVersion.V2_8}/custom_audience/delete_game_limit`,
  'GET_CUSTOM_FIELDS': `${ApiVersion.V2_9}/company/get_company_custom_fields`,
  'GET_CUSTOM_FIELDS_VALUES': `${ApiVersion.V2_9}/company/get_company_custom_field_values`,
  'GET_TIMEZONE_BY_LOCATION': `${ApiVersion.V2_8}/get_timezone_by_locations`,
  'UPDATE_LEVEL_POSITION_IN_MULTILEVEL_GAME': `${ApiVersion.V2_1}/mlg/update_mlg_level_position`,

  'GET_MULTILEVEL_GAME_ASSIGNMENT_CF': `${ApiVersion.V3_0}/mlg/get_assignment`,
  'ADD_MULTILEVEL_GAME_ASSIGNMENT_CF': `${ApiVersion.V3_0}/mlg/add_assignment`,
  'SET_MULTILEVEL_GAME_ASSIGNMENT_CF': `${ApiVersion.V3_0}/mlg/mlg_turn_on_off`,

  'UPDATE_GAME_REORDER': `${ApiVersion.V2_8}/game/update_game_position`,
  'GET_GAME_REORDER': `${ApiVersion.V2_8}/game/retrieve_game_order`,
  'GET_CONTEST_ASSIGNMENT_CF': `${ApiVersion.V2_9}/contest/get_assignment`,
  'ADD_CONTEST_ASSIGNMENT_CF': `${ApiVersion.V2_9}/contest/add_assignment`,
  'UPDATE_CONTEST_ASSIGNMENT_CF': `${ApiVersion.V2_9}/contest/update_assignment`,
  'RETRIEVE_GAME_LIMIT': `${ApiVersion.V3_0}/slg/retrieve_game_limit`,
  'ADD_GAME_LIMIT': `${ApiVersion.V3_0}/slg/add_game_limit`,
  'DELETE_GAME_LIMIT': `${ApiVersion.V3_0}/slg/delete_game_limit`,
  'UPDATE_GAME_LIMIT': `${ApiVersion.V3_0}/slg/edit_game_limit`,
  'UPDATE_GAME_ATTEMPTS': `${ApiVersion.V3_0}/slg/edit_game_attempts`,
  'GET_LIVE_GAME_SESSIONS': `${ApiVersion.V3_0}/gamelimit/retrieve_incomplete_session`,
  'GET_PLAYERS_FOR_CUSTOM_FIELDS': `${ApiVersion.V2_9}/player/retrieve_player`,
  'DOWNLOAD_PLAYERS': `${ApiVersion.V2_9}/player/download_player`,
  'GET_PLAYER_ATTEMPTS': `${ApiVersion.V2_9}/gamelimit/retrieve_game_attempt`,
  'GET_PINNED_GAMES': `${ApiVersion.V3_0}/game/get_pinned_games`,
  'UPDATE_PIN_GAMES': `${ApiVersion.V3_0}/pinned_games/pin_unpin`,
  'VIEW_LEADERBOARD': `${ApiVersion.V3_1}/leaderboard/view_company_leaderboard`,
  'UPDATE_LEADERBOARD': `${ApiVersion.V3_1}/leaderboard/schedule_leaderboard`,
  'GET_GAMES_BY_WIN_RATE': `${ApiVersion.V3_0}/game/retrieve_games`,
  'CHECK_AUDIENCE': `${ApiVersion.V2_8}/custom_audience/audience_exists`,
  'DELETE_CUSTOM_AUDIENCE_PLAYERS': `${ApiVersion.V2_8}/custom_audience/delete_audience_players`,
  'GET_PLAYERS_FOR_CUSTOM_AUDIENCE': `${ApiVersion.V2_9}/player/retrieve_player_v3`,
  'COPY_CONTEST': `${ApiVersion.V3_1}/contest/copy_contest`,
  'CONTEST_COPY_PROGRESS': `${ApiVersion.V2_1}/mlg/copy_mlg_progress`, // we are keeping endpoint similar to MLG cloning
  'GET_MLG_DETAIL_REPORT': `${ApiVersion.V3_2}/mlg/dashboard/get_mlg_detail_view`,
  'GET_MLG_PLAYER_REPORT': `${ApiVersion.V3_2}/mlg/dashboard/get_mlg_player_report`,
  

  'LEADERBOARD_BY_MLG': `${ApiVersion.V3_2}/mlg/dashboard/get_mlg_leaderboard`,
  'DASHBOARD_MLG_DETAILS': `${ApiVersion.V3_2}/mlg/dashboard/get_mlg_overall_details`,
  'DASHBOARD_MLG_CHART_DETAILS': `${ApiVersion.V3_2}/mlg/dashboard/get_mlg_total_games_played`,
  'DASHBOARD_SLG_CHART_DETAILS': `${ApiVersion.V3_3}/games/dashboard/get_slg_total_games_played`,
  'DASHBOARD_MLG_PARTICIPATION': `${ApiVersion.V3_2}/mlg/dashboard/get_mlg_participation`,
  'PERFORMANCE_LEVEL_BY_MLG': `${ApiVersion.V3_2}/mlg/dashboard/get_performance_by_level`,
  'GET_VIDEOS': `${ApiVersion.V3_2}/get/help/videos`,
  'PLAYER_DASHBOARD_LATEST_TROPHIES': `${ApiVersion.V3_2}/player/dashboard/get_latest_trophies`,
  'DASHBOARD_PLAYER_DETAILS': `${ApiVersion.V3_2}/player/dashboard/get_player_overall_details`,
  'CALENDAR_STATISTICS': `${ApiVersion.V3_2}/player/dashboard/get_calendar_statistics`,
  'GAMEPLAY_ON_DATE': `${ApiVersion.V3_2}/player/dashboard/get_game_play_data_for_date`,
  'PERFORMANCE_BY_PLAYER': `${ApiVersion.V3_2}/player/dashboard/get_performance_by_game`,
  'GET_PLAYER_CONTEST_HISTORY': `${ApiVersion.V3_2}/player/dashboard/get_player_contest_details`,
  'GET_PLAYER_CONTEST_REPORT': `${ApiVersion.V3_2}/player/dashboard/get_player_contest_report`,
  'DOWNLOAD_MLG_HISTORY': `${ApiVersion.V3_2}/player/detail_report/download_mlg_player_game_history`,
  'DOWNLOAD_CONTEST_HISTORY': `${ApiVersion.V3_2}/player/detail_report/download_contest_player_history`,

  'DASHBOARD_SLG_DETAILS': `${ApiVersion.V3_3}/games/dashboard/get_slg_overall_details`,
  'DASHBOARD_SLG_PLAYER_DETAILS': `${ApiVersion.V3_3}/games/dashboard/get_slg_player_details`,
  
  'DASHBOARD_CONTEST_DETAILS': `${ApiVersion.V3_2}/report-service/dashboard/contest/contest_details`,
  'PERFORMANCE_GAMES_BY_CONTEST': `${ApiVersion.V3_2}/report-service/dashboard/contest/performance_by_games`,
  'CONTEST_PLAYER_DASHBOARD': `${ApiVersion.V3_2}/report-service/dashboard/contest/contest_player_dashboard`,
  'UPDATE_SHOP_FOR_PLAYERS': `${ApiVersion.V3_3}/shop/update_setting`,
  'GET_SHOP_GAME': `${ApiVersion.V3_2}/shop/get_shop_games_by_name_in_admin`,
  'GET_SHOP_REPORT': `${ApiVersion.V3_3}/report/get_shop_game_report`,
  'GET_CSM_ACCOUNT': `${ApiVersion.V1_0}/csm/get_csm_users_list`,
  'GET_CSM_ACCOUNT_DETAILS':`${ApiVersion.V1_0}/csm/get_csm_user_details`,
  'ACTIVATE_DEACTIVATE_CSM_ACCOUNT': `${ApiVersion.V1_0}/csm/activate_deactivate_csm_account`,
  'EDIT_ACCOUNT': `${ApiVersion.V1_0}/csm/edit_csm_account`,
  'GET_SHOP_ALL_GAMES': `${ApiVersion.V3_2}/shop/getShopGameListForAdmin`,
  'GETUSERINFO': `${ApiVersion.V3_2}/users/get_user_information`,
  'GET_PLAYER_ALL_LOCATION': `${ApiVersion.V3_3}/players/all_location`,
  'GET_PLAYER_ALL_DEPARTMENT': `${ApiVersion.V3_3}/players/all_department`,
  'GET_GAME_LANG': `${ApiVersion.V3_3}/game/get_lang_preference`,
  'UPDATE_GAME_LANG': `${ApiVersion.V3_3}/game/update_lang_preference`,
  'GET_LOCALIZATION_PROGRESS': `${ApiVersion.V3_3}/game/get_localisation_progress`,
  'TOTAL_GAME_PLAY_REPORT': `${ApiVersion.V1_6}/report/total-game-play-report`,
  'WIN_RATE_REPORT': `${ApiVersion.V1_6}/report/win-rate-report`,
  'WIN_HISTORICAL_RATE_REPORT': `${ApiVersion.V3_9}/report/player-win-rate-report`,
  'GET_PINNED_GAMES_LIST': `${ApiVersion.V3_3}/managers/get_pinned_games_list`,
  'AI_GENERATE_QUESTIONS': `${ApiVersion.V3_5}/question/generate_question`,
  // 'AI_GENERATE_QUESTIONS_V1': `${ApiVersion.V3_5}/question/generate_question_data`,
  'AI_GENERATE_QUESTIONS_V1': `${ApiVersion.V3_5}/question/generate_question`,
  'AI_GENERATE_Add_MORE_QUESTIONS': `${ApiVersion.V3_5}/question/add_questions`,
  'AI_GENERATE_QUESTIONS_POLLING': `${ApiVersion.V3_5}/question/generated_question_progress`,
  'AI_ADD_QUESTIONS': `${ApiVersion.V3_5}/question/add-questions`,
  'UNLINK_PLAYER_FROM_PHONE': `${ApiVersion.V3_4}/auth/unlink_player`,
  'GET_PLAYER_PHONE': `${ApiVersion.V3_4}/auth/get_player_phone`,
  'GET_ALERTS': `${ApiVersion.V3_6}/pop-up-alert/get?`,
  'COMPANIES_LIST_DETAILS': `${ApiVersion.V3_4}/company/details`,
  'CALL_TO_ACTION': `${ApiVersion.V3_6}/pop-up-alert/`,
  'CREATE_ALERT': `${ApiVersion.V3_6}/pop-up-alert/add`,
  'EDIT_ALERT': `${ApiVersion.V3_6}/pop-up-alert/edit`,
  'ENABLE_DISABLE_ALERT': `${ApiVersion.V3_6}/pop-up-alert/disable?`,
  'GET_ALERT_DETAILS': `${ApiVersion.V3_6}/pop-up-alert/get_details?`,
  'GET_GLOBAL_PINNED_GAMES': `${ApiVersion.V3_8}/team/get_company_pinned_games`,
  'GET_OVERALL_DETAILS_BY_TEAM': `${ApiVersion.V3_8}/team/overall_details_by_team`,
  'SAVE_COMPANY_PINNED_GAME': `${ApiVersion.V3_8}/team/save_company_pinned_game`,
  'GET_ONLY_GAMES': `${ApiVersion.V3_8}/get_all_slg_games`,

  'GET_IP': `${ApiVersion.V3_7}/ip`,
  'ADD_IP': `${ApiVersion.V3_7}/ip`,
  'UPDATE_IP': `${ApiVersion.V3_7}/ip`,
  'DELETE_IP': `${ApiVersion.V3_7}/ip`,
  'GET_IP_EXCLUSIONS': `${ApiVersion.V3_8}/ip/exclusions`,
  'UPDATE_IP_EXCLUSIONS': `${ApiVersion.V3_8}/ip/exclusions`,

  'GET_PATHWAY_INSIGHTS': `${ApiVersion.V3_9}/report/insights/pathways`,
  'GET_ENGAGEMENT_INSIGHTS': `${ApiVersion.V3_9}/report/insights/engagement`,

  'ADD_GAME_PATHWAY': `${ApiVersion.V3_9}/pathways/add`,
  'GET_GAME_PATHWAYS': `${ApiVersion.V3_9}/pathways/get`,
  'GET_PATHWAYS_GAME_COUNT': `${ApiVersion.V3_9}/pathways/retrieve_games_count`,
  'DELETE_PATHWAYS': `${ApiVersion.V3_9}/pathways/delete`,
  'UPDATE_PATHWAY': `${ApiVersion.V3_9}/pathways/update`,
  
  'DOWNLOAD_ENGAGEMENT': `${ApiVersion.V3_9}/report/insights/engagement/download`,
  'DOWNLOAD_PATHWAY': `${ApiVersion.V3_9}/report/insights/pathways/download`,

  

  'GET_SERIES': `${ApiVersion.V3_9}/series/get`,
  'ADD_SERIES': `${ApiVersion.V3_9}/series/add`,
  'UPDATE_SERIES': `${ApiVersion.V3_9}/series/update`,
  'DELETE_SERIES': `${ApiVersion.V3_9}/series/delete`,
  'GET_GAMES_SERIES': `${ApiVersion.V3_9}/series/games/get`,

  'GET_GAMES_SLG_MLG': `${ApiVersion.V3_9}/games/playable_games`,
  'SAVE_GAMES_SERIES': `${ApiVersion.V3_9}/series/games/save`,
  'UPDATE_PDF_FILE': `${ApiVersion.V3_5}/question/upload_file`,
  'PROCESS_PDF_FILE': `${ApiVersion.V3_5}/process-pdf`,
  'GET_TRANSLATION_PROGRESS': `${ApiVersion.V3_9}/games/get_translation_progress`,
  'RETRY_TRANSLATION_PROGRESS': `${ApiVersion.V3_9}/games/retry_failed_questions`,  
};






export enum Constants {
  DEV_API_KEY = 'MIIC4DCCAcigAwIBAgIQKCF4iDA3REFS',
  DEV_API_SECRET = 'MIIC6WQIKdKgAwIBAgIQGATGYHS2YGHH',
  ACCESS_TOKEN = 'accessToken',
  ACCESS_TYPE = 'accessType',
  ROLE_ACCESS_TYPE = 'access_type',
  MANAGER = 'manager',
  PLAYER = 'player',
  PLAYER_ID = 'player_id',
  POST_LOGIN = 'post_login',
  POST_LOGIN_CUSTOM_FIELD = 'post_login_custon_field',
  ADMIN = 'admin',
  USER = 'user',
  SSO_DETAILS = 'sso_details',
  ALL = 'All',
  PLAYER_STATUS = 'Player status',
  COMPANY_NAME = 'company_name',
  COUNTRY_NAME = 'country_name',
  COUNTRY_ID = 'country_id',
  LOCATION_NAME = 'location_name',
  LOCATION_ID = 'location_id',
  LOCATION_IDS = 'location_ids',
  EVERYONE = 'everyone',
  DEPARTMENT_ID = 'department_id',
  DEPARTMENT_IDS = 'department_ids',
  DEPARTMENT_NAME = 'department_name',
  GROUP_ID = 'group_id',
  GROUP_IDS = 'group_ids',
  GROUP_NAME = 'group_name',
  STATE_NAME = 'state_name',
  STATE_ID = 'state_id',
  CREATED_ON = 'created_on',
  GAME_NAME = 'game_name',
  ATTEMPT = 'attempt',
  ATTEMPTS = 'attempts',
  CORRECT_COUNT = 'correct_ans_count',
  INCORRECT_COUNT = 'incorrect_ans_count',
  TOTAL_ATTEMPTS = 'total_attempts',
  SERVED_COUNT = 'served_question_count',
  TROPHY_NAME = 'trophy_name',
  IS_ACHIEVED = 'is_achieved',
  TROPHY_PLAYER_NAME = 'name',
  GAME_ID = 'game_id',
  GAME_TYPE = 'game_type',
  DASHBOARD_BY = 'dashboard_by',
  GAME_MODE = 'game_mode',
  INCLUDE_DELETED = 'include_deleted',
  GAME_STATE_MODE = 'game_state_mode',
  GAME_STATE = 'game_state',
  GAME_CATEGORY = 'game_category',
  GAME_CATEGORY_ID = 'game_category_id',
  PATHWAY_ID = 'pathway_id',
  QUESTION_TITLE = 'question_title',
  PLAYER_NAME = 'player_name',
  FIRST_NAME = 'first_name',
  VIP_CODE = 'vip_code',
  NAME = 'name',
  EMAIL = 'email',
  STATUS = 'status',
  TYPE = 'type',
  RATE_CATEGORY = 'rate_category',
  CATEGORY_NAME = 'category_name',
  CATEGORY_ID = 'category_id',
  QUESTION_CATEGORY_ID = 'question_category_id',
  CARD_NUMBER = 'card_number',
  QUESTION_TIME = 'time',
  QUESTION_POINTS = 'points',
  ACCURACY = 'accuracy',
  QUESTION_TYPE = 'question_type',
  QUESTION_TAGS = 'tag_keywords',
  QUESTION_STATE = 'is_active',
  IS_ACTIVE = 'is_active',
  MODE = 'mode',
  OWNER = 'owner',
  OWNER_ID = 'owner_id',
  CITY = 'city',
  INDUSTRY = 'industry',
  SEND_REPORT = 'send_report',
  ETHNICITY = 'ethnicity',
  TIME_ZONE = 'timezone',
  TIME_ZONE_NAME = 'tz_name',
  SELECTED_LOCALLY = 'en',
  FAQ_QUESTION = 'question',
  SP_GAMES = 'sp_games',
  SP_POINTS = 'sp_points',
  RESULT = 'result',
  SP_TIME = 'sp_time',
  SP_LAST_PLAYED_ON = 'sp_last_played_on',
  PLAYED_ON = 'played_on',
  MP_GAMES = 'mp_games',
  MP_POINTS = 'mp_points',
  MP_TIME = 'mp_time',
  MP_WINS = 'mp_wins',
  MP_LAST_PLAYED_ON = 'mp_last_played_on',
  PLAYER_RATING = 'player_rating',
  CONTEST_NAME = 'contest_name',
  CONTEST_STATE = 'contest_state',
  CONTEST_DETAILS = 'contest_details',
  WINNER_SCORE = 'winner_score',
  DEFEATED_PLAYER = 'defeated_player',
  MLG_NAME = 'mlg_name',
  MLG_STATE = 'mlg_state',
  MLG_COMPLETENESS = 'mlg_completeness',
  HIERARCHY = 'hierarchy',
  PAYWALL_STATUS = 'paywall_status',
  PAYWALL_END_DATE = 'paywall_end_date',
  ACCOUNT_TYPE = 'account_type',
  CSR_ID = 'csr_id',
  CSR_IDS = 'csr_ids',
  CSR_NAME = 'csr_name',
  SDR_ID = 'sdr_id',
  SDR_IDS = 'sdr_ids',
  SDR_NAME = 'sdr_name',
  HEALTH_AWARENESS = 'health_awareness',
  HUMAN_RESOURCES = 'human_resources',
  SALES = 'sales',
  CUSTOMER_RELATIONS = 'customer_relations',
  ARCHIVE = 'archive',
  GAME_SINGLE_LEVEL = 'Game - Single Level',
  GAME_MULTI_LEVEL = 'Game - Multilevel',
  LAST_PLAYED = 'last_played',
  AUDIENCE_NAME = 'audience_name',
  AUDIENCE_IDS = 'audience_ids',
  CUSTOM_AUDIENCE = 'custom_audience',
  PLAYER_COUNT = 'player_count',
  AUDIENCE = 'AUDIENCE',
  NO_AUDIENCE = 'NO_AUDIENCE_COUNT',
  LOCATION_EXIST = 'LOCATION_EXIST',
  AUDIENCE_EXIST = 'AUDIENCE_EXIST',
  LOCATION = 'LOCATION',
  WINRATE = 'winrate',
  WIN_RATE = 'win_rate',
  LAST_SCORE = 'last_score',
  HIDE_AUDIENCE = 'HIDE_AUDIENCE',
  CUSTOM_FILTER_KEY = 'customFilterKey',
  DISPLAY_WIN_RATE_BY = 'display_winrate_by',
  TOTAL_POINTS = 'total_points',
  CURRENT_LEVEL = 'current_level',
  GAME_STATUS = 'game_status',
  TIME_PLAYED = 'time_played',
  GAMES_PLAYED = 'games_played',
  GAMES_PLAY_COUNT = 'gameplay_count',
  FINAL_RANKING = 'final_ranking',
  START_DATE = 'start_date',
  NO_OF_REQUEST = 'request_count',
  PATHWAY_INSIGHT = 'pathway_insight',
  RISK = 'risk',
}

export enum PlaceholderText {
  GAME_NAME = 'Enter Game Name',
  TROPHY_NAME = 'Enter Trophy Name',
  TROPHY_PLAYER_NAME = 'Enter Player Name',
  CATEGORY_NAME = 'Enter Category Name',
  PATHWAY_NAME = 'Enter Pathway Name',
  OWNER_NAME = 'Enter Owner Name',
  GAME_TYPE = 'Enter Game Type',
  GAME_MODE = 'Enter Game Mode',
  GAME_STATE = 'Enter Game State',
  QUESTION_TITLE = 'Search Questions',
  QUESTION_TYPE = 'Enter Question Type',
  QUESTION_POINTS = 'Enter Question Points',
  QUESTION_TIME = 'Enter Question Time',
  QUESTION_TAGS = 'Enter Question Tag',
  CARD_NUMBER = 'Enter Card Number',
  QUESTION_STATE = 'Enter Question State',
  CITY_NAME = 'Enter City',
  COUNTRY_NAME = 'Enter Country',
  STATE_NAME = 'Enter State',
  COMPANY_NAME = 'Enter Company Name',
  DEPARTMENT_NAME = 'Enter Department',
  LOCATION_NAME = 'Enter Location',
  GROUP_NAME = 'Enter Group Name',
  MANAGER_NAME = 'Enter Manager Name',
  PLAYER_NAME = 'Enter Player Name',
  EMAIL = 'Enter Email',
  TYPE = 'Enter Manager Type',
  STATUS = 'Enter Status',
  VIP_CODE = 'Enter Code',
  CONTEST_NAME = 'Enter Contest Name',
  CONTEST_STATE = 'Enter Contest State',
  MLG_NAME = 'Enter Multilevel Game Name',
  MLG_STATE = 'Enter Multilevel Game State',
  MLG_COMPLETENESS = 'Enter Multilevel Game Completeness',
  PAYWALL_STATUS = 'Enter Paywall Status',
  ACCOUNT_TYPE = 'Enter Account Type',
  HIERARCHY_STATE = 'Enter Hierarchy State',
  CSR_NAME = 'Enter CSR Name',
  SDR_NAME = 'Enter SDR Name',
  AUDIENCE_NAME = 'Enter Audience Name',
  WIN_RATE = 'Enter Win Rate Range',
  PATHWAY_INSIGHT = 'Pathway Insight',

}

export enum ErrorCode {
  COMPANY_SLUG_NOT_MATCH = 757,
  ACCOUNT_DEACTIVATED = 784,
  EMAIL_NOT_REGISTERED = 793,
  INVALID_CREDENTIALS = 707,
  COMPANY_NOT_RECOGNIZE = 2002,
  EMAIL_NOT_RECOGNIZE = 775,
  EMAIL_N_PWD_NOT_MATCH = 717,
  EMAIL_PWD_NOT_MATCH = 2008,
  INACTIVE_CONTACT_MANAGER = 776,
  PROBLEM_WITH_SENDING_EMAIL = 766,
  PASSWORD_NOT_MATCH = 300008,
  PASSWORD_RESET_LINK_SENT = 831,
  DEPT_NAME_EXIST = 304008,
  INVALID_DEPT_NAME = 304010,
  UNAUTHORIZE_ACCESS = 311000,
  INVALID_SORTING_KET = 100084,
  INVALID_ORDER_BY = 100085,
  INVALID_START_INDEX = 100086,
  INVALID_LIMIT_VALUE = 100087,
  EMAIL_ID_EXIST = 301015,
  PWD_CONFIRM_PWD_NT_MATCH = 301013,
  EMAIL_ID_INVALID = 301008,
  GAME_NOT_READY = 306024,
  PROFILE_NAME = 316012,
  PROFILE_SCANARIO = 316015,
  PROFILE_TITLEDESCRIPTION = 316020,
  PROFILE_SCANARIO_REQUIRED = 316010,
  PROFILE_SAVED = 316002,
  PLAYER_LINKED_TO_GROUP = 305002,
  PLAYER_LINKED_TO_DEPARTMENT = 304015,
  PLAYER_LINKED_TO_LOCATION = 303025,
  GAME_NAME_VALIDATION = 306021,
  UNABLE_TO_DELETE_CATEGORY = 315010,
  INVALID_EMAILS = 309003,
  CAT_LENGTH_EXCEED = 307039,
  RESET_PWD_LINK_EXPIRE = 3000091,
  ERROR_UPDATING_PASSWORD = 300009,
  PASSWORD_UPDATED_SUCCESSFULLY = 301000,
  CSV_HEADER_INCORRECT = 301043,
  CAT_VALIDATION = 307014,
  DUPLICATE_COMPANY = 300006,
  USER_NAME_VALIDATION = 785,
  GLOBALID_EXIST = 301053,
  USERNAME_EXIST = 301024,
  SLUG_EXIST = 305051,
  VIP_CODE_EXISTS = 420008,
  CONTEST_NAME_VALIDATION = 177013, // change me
  CONTEST_CREATED = 319015,
  UNABLE_TO_SCHEDULE_CONTEST = 319026,
  CONTEST_NOT_IN_READY_STATE = 319052,
  UNABLE_TO_MOVE_CONTEST_IN_DRAFT = 319053,
  SHOP_GAME_LIMIT_EXCEEDED = 450005,
  SHOP_GAME_EXIST_IN_LIBRARY = 450006,
  CATEGORY_ALREDY_EXIST = 460500,
  PATHWAY_ALREDY_EXIST = 701011,
  UPDATE_PATHWAY_ALREDY_EXIST = 701012,
  PLAYER_LIMIT_EXCEEDED = 3000031,
  MANAGER_LIMIT_EXCEEDED = 3000032,
  GAME_LIMIT_EXCEEDED = 3000033,
  COMPANY_METRICS_LIMIT_EXCEEDED = 3000034,
  LIVE_GAME_DELETE_RESTRICTION = 306055,
  RESTRICT_GAME_DELETE_ON_CONTEST_MLG = 306054,
  INACTIVE_PLAYERS = 3000042,
  AUDIENCE_EXIST = 3000037,
  LIVE_GAME_AUDIENCE_DELETE_RESTRICTION = 3000044,
  RESTRICT_DISABLE_LEVEL_IN_LIVE_MLG = 3000125,
  RESTRICT_TO_CHANGE_SLG_ASSIGNMENT = 123314,
  UNABLE_TO_PIN_MULTIPLAYER_GAMES = 5000057,
  MIDMANAGER_TEAMLEAD_LINKED_TO_LOCATION = 406001,
  MIDMANAGER_TEAMLEAD_LINKED_TO_DEPARTMENT = 405001,
  LIMIT_50_LOCATIONS = 5000006,
  LIMIT_50_DEPARTMENTS = 5000005,
  RESTRICT_TO_DEACTIVATE_QUESTION_IN_LIVE_SLG = 318002,
  CONFIG_ADMIN_DOWN = 404404,
  REACTIVATE_CSM_ACCOUNT = 432459,
  DEACTIVATE_CSM_ACCOUNT = 432460,
  LOC_DEPT_ALREADY_EXIST = 424242,
  QUESTION_TRANSLATION_COMPLETE = 420022,
  CHATGPT_TIMEOUT = 116622,
  CONSUMER_ID_DOSENT_EXIST = 900008,
  MULTIPLE_CONSUMER_ID_EXIST = 900007,
  ALERTS_CREATED = 654752,
  ALERTS_UPDATED = 654753,
  ALERTS_DATE_ERROR = 654757,
  SHOP_DISABLE_ERROR = 654759,
  AI_NOT_ENABLE_ERROR = 701001,
  AI_TOKEN_NOT_SET_ERROR = 701002,
  AI_TOKEN_EXHAUSTED_ERROR = 701003,
  AI_LESS_CONTENT_TOGENERATE = 405002,
  AI_PDF_IS_BLANK = 405003,
  AI_PDF_PAGES_LIMIT = 405004,  
  AI_REQUEST_TIMEOUT = 404001,
  AI_INVALID_RES = 405006,
  AI_REQUEST_RUN_ERROR = 405005,
  AI_MAX_QUESTIONS_GENERATED = 405010,
  AI_PDF_CONTENT_LONG = 405011,


  // change code
}
const ErrorMessage = {
  'COMPANY_SLUG_NOT_MATCH': 'Company ID is not valid.',
  'ACCOUNT_DEACTIVATED': 'Your account has been deactivated, please contact your admin.',
  'EMAIL_NOT_REGISTERED': 'Your email is not registered. Please contact your admin.',
  'INVALID_CREDENTIALS': 'Invalid credentials, please contact 1huddle team.',
  'COMPANY_NOT_RECOGNIZE': 'We could not recognize your company, please contact your admin.',
  'EMAIL_NOT_RECOGNIZE': 'We could not recognize your email address.',
  'EMAIL_N_PWD_NOT_MATCH': 'Email address and password do not match.',
  'EMAIL_PWD_NOT_MATCH': 'Email address and password do not match.',
  'INACTIVE_CONTACT_MANAGER': 'Your account has been deactivated, please contact your manager.',
  'PROBLEM_WITH_SENDING_EMAIL': 'There was problem while sending email, please try again.',
  'PASSWORD_NOT_MATCH': 'The new password and confirmation password do not match.',
  'PASSWORD_RESET_LINK_SENT': 'Password has been reset. Please check your email.',
  'DEPT_NAME_EXIST': 'Department already exist.',
  'INVALID_DEPT_NAME': 'Not a valid Departement.',
  'UNAUTHORIZE_ACCESS': 'You are not authorized to access this page.',
  'EMAIL_ID_EXIST': 'Entered email already registered with us.',
  'PWD_CONFIRM_PWD_NT_MATCH': 'Password and confirm password do not match.',
  'EMAIL_ID_INVALID': 'Please enter valid email.',
  'GAME_NOT_READY': 'This game cannot be moved to ready yet. Please add required fields.',
  'PROFILE_NAME': 'Profile name should be at least 4 characters long.',
  'PROFILE_SCANARIO': 'Please enter scenario.',
  'PROFILE_TITLEDESCRIPTION': 'Title & description should be at least 2 characters long.',
  'PROFILE_SCANARIO_REQUIRED': 'Scenario text is required.',
  'PROFILE_SAVED': 'Profile added successfully.',
  'PLAYER_LINKED_TO_GROUP': 'Groups which have players cannot be deleted.',
  'PLAYER_LINKED_TO_DEPARTMENT': 'Departments which have players cannot be deleted.',
  'PLAYER_LINKED_TO_LOCATION': 'Locations which have players cannot be deleted.',
  'GAME_NAME_VALIDATION': 'Game name should be in between 4 to 45 characters.',
  'UNABLE_TO_DELETE_CATEGORY': 'You cannot delete category because someone has played this game.',
  'INVALID_EMAILS': 'Please enter valid emails ids.',
  'CAT_LENGTH_EXCEED': 'You cannot add more than 5 categories.',
  'RESET_PWD_LINK_EXPIRE': 'Reset Password link is no more valid.',
  'ERROR_UPDATING_PASSWORD': 'There was a problem while updating your password. Please try again.',
  'PASSWORD_UPDATED_SUCCESSFULLY': 'Password changed successfully.',
  'CSV_HEADER_INCORRECT': 'Headers in selected CSV are incorrect',
  'DUPLICATE_COMPANY': 'Company name already exists.',
  'USER_NAME_VALIDATION': 'Username is not registered with 1Huddle. Please contact your admin.',
  'GLOBALID_EXIST': 'Global ID already exists.',
  'USERNAME_EXIST': 'Username already exists.',
  'SLUG_EXIST': 'Company ID already exists.',
  'VIP_CODE_EXISTS': 'VIP Code already exists. Please create a unique code.',
  'CONTEST_NAME_VALIDATION': 'Contest name should be in between 1 to 45 characters.',
  'CONTEST_CREATED': 'Contest created successfully',
  'UNABLE_TO_SCHEDULE_CONTEST': 'Unable to schedule contest',
  'CONTEST_NOT_IN_READY_STATE': 'This contest can not be moved to DRAFT, contest may not be in READY state',
  'UNABLE_TO_MOVE_CONTEST_IN_DRAFT': 'Unable to move contest to DRAFT.',
  'CATEGORY_ALREDY_EXIST': 'This category already exists.',
  'PATHWAY_ALREDY_EXIST': 'This pathway already exists.',
  'UPDATE_PATHWAY_ALREDY_EXIST': 'This pathway already exists.',
  'COMPANY_METRICS_LIMIT_EXCEEDED': 'Limit cannot be lower than the current count.',
  'LIVE_GAME_DELETE_RESTRICTION': 'You can not delete this game, either game is live or scheduled',
  'RESTRICT_GAME_DELETE_ON_CONTEST_MLG': 'Oops! One or more games have been deleted. Please remove deleted games.',
  'MIDMANAGER_TEAMLEAD_LINKED_TO_LOCATION': 'Locations which have Mid Managers/Team Lead cannot be deleted.',
  'MIDMANAGER_TEAMLEAD_LINKED_TO_DEPARTMENT': 'Departments which have Mid Managers/Team Lead cannot be deleted.',
  'LIMIT_50_LOCATIONS': 'You can only add up to 50 locations.',
  'LIMIT_50_DEPARTMENTS': 'You can only add up to 50 departments.',
  'RESTRICT_TO_DEACTIVATE_QUESTION_IN_LIVE_SLG': 'This game is currently live. At least one question is needed in a live game.',
  'LOC_DEPT_ALREADY_EXIST': 'Selected Primary location/department is already part of secondary fields.',
  'QUESTION_TRANSLATION_COMPLETE': 'This question is part of a Live game. Please complete translations to activate it',
  'CHATGPT_TIMEOUT': 'It is taking longer than usual to genrate questions. Please try again later.',
  'CONSUMER_ID_DOSENT_EXIST': 'No phone number is currently associated with this account. The player can link the account with any phone number.',
  'MULTIPLE_CONSUMER_ID_EXIST': 'No phone number is currently associated with this account. The player can link the account with any phone number.',
  'ALERTS_CREATED': 'Alert created successfully.',
  'ALERTS_UPDATED': 'Alert updated successfully.',
  'ALERTS_DATE_ERROR': 'Please check the date range.',
  'SHOP_DISABLE_ERROR': 'Shop is disable for this company.',
  'AI_NOT_ENABLE_ERROR': 'AI not enabled for this company.',
  'AI_TOKEN_NOT_SET_ERROR': 'AI token limit is not set for this company.',
  'AI_TOKEN_EXHAUSTED_ERROR': 'You have reached your monthly usage limit for AI Assist. Please contact your 1Huddle representative.',
  'AI_LESS_CONTENT_TOGENERATE': "Oops! Questions couldn't be generated. Try refining your input.",
  'AI_MAX_QUESTIONS_GENERATED': "Great work! You've generated the maximum available questions for this prompt/content.",
  'AI_PDF_CONTENT_LONG': "The uploaded PDF is too large to process. Please upload a smaller file.",
  'AI_PDF_PAGES_LIMIT': "The uploaded PDF exceeds the maximum limit of 100 pages. Please upload a PDF with 100 pages or fewer.",
  'AI_PDF_IS_BLANK': "The uploaded PDF blank.",
  'AI_REQUEST_TIMEOUT': "Aw, Snap! Questions couldn't be generated. Please try again.",
  'AI_INVALID_RES': "Aw, Snap! Questions couldn't be generated. Please try again.",
  'AI_REQUEST_RUN_ERROR': "Aw, Snap! Questions couldn't be generated. Please try again.",
  

    
};

@Injectable({
  providedIn: 'root'
})

export class ApiService {

  constructor() { }

  getErrorMessage(errorCode) {    
    console.log('Error Code: ' + ErrorMessage[errorCode]);
    if (errorCode && ErrorCode[errorCode]) {
      return ErrorMessage[errorCode];
    }
    return 'Aw, Snap! Something went wrong. Check your connection and try again.';
  }
}
